<html>
	<head></head>
	<body>
		<p>
    		Date: <?php echo date('m/d/Y H:i:s'); ?><br />
    		Request type: <?php echo htmlspecialchars($request_type); ?><br />
    		URL: <a href="<?php echo htmlspecialchars($url); ?>"><?php echo htmlspecialchars($url); ?></a><br />
    		<?php if ($request_data_url): ?>
    		Request data: <a href="<?php echo htmlspecialchars($request_data_url); ?>"><?php echo htmlspecialchars($request_data_url); ?></a>
    		<?php endif; ?>
		</p>
		<p>
			<?php echo nl2br(htmlspecialchars($description)); ?>
		</p>
		<hr />
		<font size="-1" color="#ccc">
			E-mail sent from IP: <?php echo htmlspecialchars($_SERVER['REMOTE_ADDR']); ?><br />
			User Agent: <?php echo htmlspecialchars($_SERVER['HTTP_USER_AGENT']); ?>
		</font>
	</body>
</html>