	<tr>
		<th colspan="2">
			<input type="hidden" name="cdn.ftp.pasv" value="0" />
			<label><input id="cdn_ftp_pasv" type="checkbox" name="cdn.ftp.pasv" value="1"<?php checked($this->_config->get_boolean('cdn.ftp.pasv'), true); ?> /> Use passive <acronym title="File Transfer Protocol">FTP</acronym> mode</label><br />
			<span class="description">Enable this option only if there are connectivity issues, otherwise it's not recommended.</span>
		</th>
	</tr>
	<tr>
		<th style="width:300px;"><label for="cdn_ftp_host"><acronym title="File Transfer Protocol">FTP</acronym> hostname:</label></th>
		<td>
			<input id="cdn_ftp_host" type="text" name="cdn.ftp.host" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.ftp.host')); ?>" size="30" /><br />
			<span class="description">Specify the server's address, e.g.: "ftp.domain.com". Use "127.0.0.1" if using a sub-domain on the same server as your site.</span>
		</td>
	</tr>
	<tr>
		<th><label for="cdn_ftp_user"><acronym title="File Transfer Protocol">FTP</acronym> username:</label></th>
		<td>
			<input id="cdn_ftp_user" type="text" name="cdn.ftp.user" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.ftp.user')); ?>" size="30" />
		</td>
	</tr>
	<tr>
		<th><label for="cdn_ftp_pass"><acronym title="File Transfer Protocol">FTP</acronym> password:</label></th>
		<td>
			<input id="cdn_ftp_pass" type="text" name="cdn.ftp.pass" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.ftp.pass')); ?>" size="30" />
		</td>
	</tr>
	<tr>
		<th><label for="cdn_ftp_path"><acronym title="File Transfer Protocol">FTP</acronym> path:</label></th>
		<td>
			<input id="cdn_ftp_path" type="text" name="cdn.ftp.path" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.ftp.path')); ?>" size="30" /><br />
			<span class="description">Specify the directory where files must be uploaded to be accessible in a web browser.</span>
		</td>
	</tr>
	<tr>
		<th><label for="cdn_ftp_domain">Replace site's hostname with:</label></th>
		<td>
			<input id="cdn_ftp_domain" type="text" name="cdn.ftp.domain" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.ftp.domain')); ?>" size="30" /><br />
			<span class="description">Enter the hostname of your FTP server configured above, this value will replace your blog's hostname in the <acronym title="Hypertext Markup Language">HTML</acronym>.</span>
		</td>
	</tr>
	<tr>
		<th colspan="2"><input id="test_ftp" class="button" type="button" value="Test FTP server" /> <span id="test_ftp_status" class="w3tc-status w3tc-process"></span></th>
	</tr>