	<tr>
		<th style="width:300px;"><label for="cdn_mirror_domain">Replace site's hostname with:</label></th>
		<td>
			<input id="cdn_mirror_domain" type="text" name="cdn.mirror.domain" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.mirror.domain')); ?>" size="30" /><br />
			<span class="description">Enter the hostname provided by your <acronym>CDN</acronym> provider, this value will replace your site's hostname in the <acronym title="Hypertext Markup Language">HTML</acronym>.</span>
		</td>
	</tr>