<table class="form-table">
    <tr valign="top">
        <th scope="row"><label for="theme_my_login_page_id"><?php _e('Page ID', 'theme-my-login'); ?></label></th>
        <td>
            <input name="theme_my_login[page_id]" type="text" id="theme_my_login_page_id" value="<?php echo (int) $theme_my_login->options['page_id']; ?>" class="small-text" />
            <p class="description"><?php _e('This should be the ID of the WordPress page that includes the [theme-my-login] shortcode. By default, this page is titled "Login".'); ?></p>
        </td>
    </tr>
    <tr valign="top">
        <th scope="row"><?php _e('Pagelist', 'theme-my-login'); ?></th>
        <td>
            <input name="theme_my_login[show_page]" type="checkbox" id="theme_my_login_show_page" value="1"<?php checked(1, $theme_my_login->options['show_page']); ?> />
            <label for="theme_my_login_show_page"><?php _e('Show Page In Pagelist', 'theme-my-login'); ?></label>
            <p class="description"><?php _e('Enable this setting to add login/logout links to the pagelist generated by functions like wp_list_pages() and wp_page_menu().', 'theme-my-login'); ?></p>
        </td>
    </tr>
    <tr valign="top">
        <th scope="row"><?php _e('Links', 'theme-my-login'); ?></th>
        <td>
            <input name="theme_my_login[rewrite_links]" type="checkbox" id="theme_my_login_rewrite_links" value="1"<?php checked(1, $theme_my_login->options['rewrite_links']); ?> />
            <label for="theme_my_login_rewrite_links"><?php _e('Rewrite Login Links', 'theme-my-login'); ?></label>
            <p class="description"><?php _e('Enable this setting to rewrite links generated by functions like wp_loginout() and wp_register().', 'theme-my-login'); ?></p>
        </td>
    </tr>	
    <tr valign="top">
        <th scope="row"><?php _e('Stylesheet', 'theme-my-login'); ?></th>
        <td>
            <input name="theme_my_login[enable_css]" type="checkbox" id="theme_my_login_enable_css" value="1"<?php checked(1, $theme_my_login->options['enable_css']); ?> />
            <label for="theme_my_login_enable_css"><?php _e('Enable "theme-my-login.css"', 'theme-my-login'); ?></label>
            <p class="description"><?php _e('In order to keep changes between upgrades, you can store your customized "theme-my-login.css" in your current theme directory.', 'theme-my-login'); ?></p>
        </td>
    </tr>
    <?php do_action('tml_settings_basic', $theme_my_login->options); ?>
</table>