<h3>Support Us</h3>

<p>We noticed you've been using W3 Total cache for at least 30 days, would you like to help us improve WordPress?</p>

<form action="options-general.php?page=<?php echo W3TC_FILE; ?>&amp;tab=<?php echo $this->_tab; ?>&amp;save_support_us" method="post">
    <p>
    	<label>
        	Link to us:
        	<select name="support" class="select-support-type">
        		<option value="">select one</option>
                <?php foreach ($supports as $support_id => $support_name): ?>
            	<option value="<?php echo $support_id; ?>"><?php echo htmlspecialchars($support_name); ?></option>
            	<?php endforeach; ?>
        	</select>
        </label>, tell your friends with a <input type="button" class="button button-tweet" value="tweet" /> and give us a great <input type="button" class="button button-rating" value="rating" />.
    </p>
    
    <div style="text-align:center;">
        <h3>THANK YOU!</h3>
        <p>
        	<input type="submit" class="button-primary" value="Save and close"> or
        	<?php echo $this->button_hide_note('Don\'t show this message again', 'support_us'); ?>
        </p>
    </div>
</form>