<h3>Tweet</h3>

<p>Enter your username (email), password and click "Tweet!" to support us!</p>

<p>This is the message that will be tweeted:</p>

<blockquote>I just optimized my #wordpress blog's performance using the W3 Total Cache #plugin by @<a href="http://twitter.com/w3edge" target="_blank">w3edge</a>. Check it out! <a href="http://j.mp/A69xX" target="_blank">http://j.mp/A69xX</a></blockquote>

<form action="">
	<table class="form-table">
		<tr>
			<th><label for="tweet_username">Username:</label></th>
			<td><input id="tweet_username" type="text" size="30" /></td>
		</tr>
		<tr>
			<th><label for="tweet_password">Password:</label></th>
			<td><input id="tweet_password" type="password" size="30" /></td>
		</tr>
	</table>
	
    <p class="submit">
    	<input type="submit" name="Submit" class="button-primary" value="Tweet!" />
    </p>
</form>

<p><em>Your password is not saved. Your tweet is submitted directly to twitter.com via their <acronym title="Application Programming Interface">API</acronym>.</em></p>
